services:
  web:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env

  web_migrate:
    extends:
      service: web
    command: python manage.py reset

  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
